spring.application.name=gestion-guias

# Puerto donde se expone la API
server.port=8080

# Configuracion de base de datos H2 en archivo
spring.datasource.url=jdbc:h2:file:./data/guiasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA actualiza las tablas automaticamente segun las entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola web de H2 para revisar la base de datos local
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Ruta temporal donde se generan las guias
# En EC2 esta ruta se conecta a EFS mediante Docker
app.storage.local-path=./storage/guias

# Configuracion de AWS
aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${S3_BUCKET_NAME:gestion-guias-s3}

# Azure AD B2C - Validador JWT
# Issuer exacto que aparece en el token generado por el User Flow
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://guiasdespachopedro2026.b2clogin.com/tfp/fa27e159-24ef-467f-bb9d-8810394076da/b2c_1_guias_signin/v2.0/

# Claves publicas usadas para validar la firma RS256 del token
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://guiasdespachopedro2026.b2clogin.com/tfp/fa27e159-24ef-467f-bb9d-8810394076da/b2c_1_guias_signin/discovery/v2.0/keys

# Claim personalizado usado para controlar permisos por rol
app.security.claim-role=extension_guiaRole

# RabbitMQ - Configuracion para mensajeria asincrona S8
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guias_user}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guias_pass}

# RabbitMQ - Nombres de exchange, colas y routing keys
app.rabbitmq.exchange=guias.exchange
app.rabbitmq.queue.pendientes=guias.pendientes.queue
app.rabbitmq.queue.errores=guias.errores.queue
app.rabbitmq.routing.pendientes=guias.pendientes
app.rabbitmq.routing.errores=guias.errores

# Actuator - Endpoints de monitoreo
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always