spring.application.name=gestion-guias

# Puerto donde se expone la API
server.port=8080

# Configuracion de base de datos H2 en archivo
spring.datasource.url=jdbc:h2:file:./data/guiasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA actualiza las tablas automaticamente segun las entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola web de H2 para revisar la base de datos local
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Ruta temporal donde se generan las guias
# En EC2 esta ruta se conecta a EFS mediante Docker
app.storage.local-path=./storage/guias

# Configuracion de AWS
aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${S3_BUCKET_NAME:gestion-guias-s3}